language: android
android:
  components:
    - build-tools-24.0.2
    - android-24
    - extra
script: ./gradlew install
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  - ./gradlew :krv:bintrayUpload -PreleaseVersion=${TRAVIS_TAG:1}
  on:
    tags: true