language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-24.0.2
    - android-24
    - extra
script: ./gradlew build -x lint
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
after_success:
  - if [ ! -z $TRAVIS_TAG ]; then ./gradlew :krv:bintrayUpload -PreleaseVersion=${TRAVIS_TAG:1}; fi